FROM golang:1.21.0-alpine3.18 AS builder

RUN apk update
RUN apk upgrade

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./

RUN go build -o /app/mochi cmd/nossl/main.go

FROM alpine

RUN apk update
RUN apk upgrade
RUN apk add bash

WORKDIR /
COPY --from=builder /app/mochi .
COPY run.sh /run.sh

RUN chmod +x /run.sh

EXPOSE 80

# tcp
EXPOSE 1883

# websockets
EXPOSE 1882

# dashboard
EXPOSE 8080

# api
EXPOSE 8081

CMD ["/bin/bash","-c","/run.sh"]